### ISSUE TITLE
error in database

### ISSUE THREAD

**Issue by sdgroeve** [chhh/MSFragger-GUI#12]
Hi

I get the following error for the last command in the GUI:

```
Executing command:
$> /home/compomics/Downloads/philosopher_linux_amd64 database --annotate /home/compomics/Downloads/MSFragger_20170103/all.revCat.fasta 
Process started
time="15:16:15" level=info msg="Processing database"

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/prvst/cmsl/db.ProcessUniProtKB(0xc4201b1a79, 0x5, 0xc4201c5680, 0x235, 0xadf157, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/home/felipevl/go/src/github.com/prvst/cmsl/db/db.go:132 +0xbc9
github.com/prvst/philosopher/lib/data.(*Base).ProcessDB(0xc4201d0000, 0x7fff410b061d, 0x3d, 0xadf157, 0x4, 0xddf560)
	/home/felipevl/go/src/github.com/prvst/philosopher/lib/data/data.go:78 +0x673
github.com/prvst/philosopher/cmd.glob..func4(0x2c5d840, 0xc4201bd0c0, 0x0, 0x2)
	/home/felipevl/go/src/github.com/prvst/philosopher/cmd/database.go:33 +0x5ff
github.com/spf13/cobra.(*Command).execute(0x2c5d840, 0xc4201bd080, 0x2, 0x2, 0x2c5d840, 0xc4201bd080)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:653 +0x299
github.com/spf13/cobra.(*Command).ExecuteC(0x2c5ec80, 0x1, 0x0, 0x0)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:728 +0x339
github.com/spf13/cobra.(*Command).Execute(0x2c5ec80, 0x0, 0x2c5eec0)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:687 +0x2b
github.com/prvst/philosopher/cmd.Execute()
	/home/felipevl/go/src/github.com/prvst/philosopher/cmd/root.go:31 +0x2d
main.main()
	/home/felipevl/go/src/github.com/prvst/philosopher/main.go:6 +0x20

Process finished, exit value: 2
```

Not sure what I do wrong...

**Comment by chhh** [comment]
@sdgroeve Which verison of Philosopher are you using? Just run it without any parameters to see the version.

**Comment by sdgroeve** [comment]
I'm using version 1.5.

**Comment by chhh** [comment]
@sdgroeve Sorry, didn't notice your update. Could you please use Philosopher 1.7? (https://github.com/prvst/philosopher/releases/latest)
AFAIK, a lot has changed in Philosopher over the last several versions.
