### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by agamu** [chhh/MSFragger-GUI#19]
Dear all,

I am trying to try the MSFragger sw, with a mzXML file (converted from RAW using msconvert) 
` java -jar MSFragger.jar fragger_open.params 00523_A10_P003818_B0A_A00_R1.mzXML`
and it gives the following error

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NumberFormatException: For input string: "0,000000"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at ad.a(Unknown Source)
        at ad.a(Unknown Source)
        at ad.<init>(Unknown Source)
        at MSFragger.main(Unknown Source)
        ... 5 more

```
What's wrong? 

Thanks in advance.
Alba.

**Comment by agamu** [comment]
Solved! I had an issue with the parameter files (I was using an old one) and there were colons (0,00000) for floating values. My bad, I was checking the wrong parameter file :S 
Sorry for the inconvenience

**Comment by chhh** [comment]
@agamu Glad to hear it has been resolved ;)
