### ISSUE TITLE
Error when running the GUI

### ISSUE THREAD

**Issue by JesseIL** [chhh/MSFragger-GUI#20]
Hi, I tried searching a file (*.mzML) and got the error below. What is the problem here?
Thanks,

Yishai

```
Will execute 13 commands:
java -jar D:\MSFragger-GUI_v3.0\MSFragger_20170103_v2\MSFragger_20170103\MSFragger.jar D:\Temp\fragger.params P:\Projects\Instrument_benchmarking\prot_repo\old\HF1_pierce_hela_120717_01.mzML 

java -cp D:\MSFragger-GUI_v3.0\MSFragger-GUI.jar umich.msfragger.util.FileMove P:\Projects\Instrument_benchmarking\prot_repo\old\HF1_pierce_hela_120717_01.pepXML D:\Temp\HF1_pierce_hela_120717_01.pepXML 

philosopher_windows_amd64.exe workspace --init 

philosopher_windows_amd64.exe peptideprophet --decoy rev --decoyprobs --ppm --accmass --nonparam --expectscore --database P:\Databases\2017_08_Working_DBs\Human\Human_SP_2017_Aug_crap.fasta D:\Temp\HF1_pierce_hela_120717_01.pepXML 

philosopher_windows_amd64.exe workspace --clean 

philosopher_windows_amd64.exe workspace --init 

philosopher_windows_amd64.exe proteinprophet --output interact interact-HF1_pierce_hela_120717_01.pep.xml 

philosopher_windows_amd64.exe workspace --clean 

philosopher_windows_amd64.exe workspace --init 

philosopher_windows_amd64.exe database --annotate P:\Databases\2017_08_Working_DBs\Human\Human_SP_2017_Aug_crap.fasta 

philosopher_windows_amd64.exe filter --sequential --mapmods --pepxml D:\Temp --protxml D:\Temp\interact.prot.xml 

philosopher_windows_amd64.exe report 

philosopher_windows_amd64.exe workspace --clean 

~~~~~~~~~~~~~~~~~~~~~~


Executing command:
$> java -jar D:\MSFragger-GUI_v3.0\MSFragger_20170103_v2\MSFragger_20170103\MSFragger.jar D:\Temp\fragger.params P:\Projects\Instrument_benchmarking\prot_repo\old\HF1_pierce_hela_120717_01.mzML 
Process started
Peptide index read in 170ms
Selected fragment tolerance 0.02 Da and maximum fragment slice size of 23710.23MB

171344664 fragments to be searched in 1 slices (1.28GB total)
Operating on slice 1 of 1: 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: umich/ms/fileio/filetypes/LCMSDataSource
	at m.d(Unknown Source)
	at m.a(Unknown Source)
	at MSFragger.main(Unknown Source)
	... 5 more
Caused by: java.lang.ClassNotFoundException: umich.ms.fileio.filetypes.LCMSDataSource
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more

4686ms
	HF1_pierce_hela_120717_01.mzML 
Process finished, exit value: 1

Executing command:
$> java -cp D:\MSFragger-GUI_v3.0\MSFragger-GUI.jar umich.msfragger.util.FileMove P:\Projects\Instrument_benchmarking\prot_repo\old\HF1_pierce_hela_120717_01.pepXML D:\Temp\HF1_pierce_hela_120717_01.pepXML 
Process started
File does not exist: P:\Projects\Instrument_benchmarking\prot_repo\old\HF1_pierce_hela_120717_01.pepXML
Process finished, exit value: 1

Executing command:
$> philosopher_windows_amd64.exe workspace --init 
Process started
INFO[09:29:04] Creating workspace                           
WARN[09:29:04] existing workspace detected, will not overwrite 
INFO[09:29:04] Done                                         

Process finished, exit value: 0

Executing command:
$> philosopher_windows_amd64.exe peptideprophet --decoy rev --decoyprobs --ppm --accmass --nonparam --expectscore --database P:\Databases\2017_08_Working_DBs\Human\Human_SP_2017_Aug_crap.fasta D:\Temp\HF1_pierce_hela_120717_01.pepXML 
Process started

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure[abi:cxx11]> >'
  what():  failed opening file: The system cannot find the file specified.

: iostream error

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure[abi:cxx11]> >'
  what():  failed opening file: The system cannot find the file specified.

: iostream error

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure[abi:cxx11]> >'
  what():  failed opening file: The system cannot find the file specified.

: iostream error


  - D:\Temp\interact-HF1_pierce_hela_120717_01.pep.xml
using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "rev".
Decoy Probabilities will be reported.
Using non-parametric distributions

INFO[09:29:05] Done                                         

Process finished, exit value: 0

Executing command:
$> philosopher_windows_amd64.exe workspace --clean 
Process started
INFO[09:29:05] Removing workspace                           
WARN[09:29:05] cannot remove the meta data: remove .meta\meta.bin: The process cannot access the file because it is being used by another process. 
INFO[09:29:05] Done                                         

Process finished, exit value: 0

Executing command:
$> philosopher_windows_amd64.exe workspace --init 
Process started
INFO[09:29:05] Creating workspace                           
WARN[09:29:05] existing workspace detected, will not overwrite 
INFO[09:29:05] Done                                         

Process finished, exit value: 0

Executing command:
$> philosopher_windows_amd64.exe proteinprophet --output interact interact-HF1_pierce_hela_120717_01.pep.xml 
Process started
2017/11/05 09:29:06 open C:\Users\bsyishai\AppData\Local\Temp\1\fea1b2d5-3247-432e-9a3d-9d13835f5b1e\interact.prot.xml: The system cannot find the file specified.

ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.0.1 Post-Typhoon dev, Build 201705191533-7588 (Windows_NT-x86_64))
Error!  Input file not found: D:/Temp/interact-HF1_pierce_hela_120717_01.pep.xml
Exiting

Process finished, exit value: 1

Executing command:
$> philosopher_windows_amd64.exe workspace --clean 
Process started
INFO[09:29:06] Removing workspace                           
WARN[09:29:06] cannot remove the meta data: remove .meta\meta.bin: The process cannot access the file because it is being used by another process. 
INFO[09:29:06] Done                                         

Process finished, exit value: 0

Executing command:
$> philosopher_windows_amd64.exe workspace --init 
Process started
INFO[09:29:06] Creating workspace                           
WARN[09:29:06] existing workspace detected, will not overwrite 
INFO[09:29:06] Done                                         

Process finished, exit value: 0

Executing command:
$> philosopher_windows_amd64.exe database --annotate P:\Databases\2017_08_Working_DBs\Human\Human_SP_2017_Aug_crap.fasta 
Process started
INFO[09:29:06] Processing database                          

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/prvst/cmsl/db.ProcessUniProtKB(0xc0421cab81, 0x9, 0xc0421d3c60, 0x16, 0xad4e7e, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/home/felipevl/go/src/github.com/prvst/cmsl/db/db.go:132 +0xbe5
github.com/prvst/philosopher/lib/data.(*Base).ProcessDB(0xc04203ca80, 0xc042010140, 0x43, 0xad4e7e, 0x4, 0xad4c4a)
	/home/felipevl/go/src/github.com/prvst/philosopher/lib/data/data.go:78 +0x6a1
github.com/prvst/philosopher/cmd.glob..func4(0x2c8ed80, 0xc0421ba960, 0x0, 0x2)
	/home/felipevl/go/src/github.com/prvst/philosopher/cmd/database.go:33 +0x48a
github.com/spf13/cobra.(*Command).execute(0x2c8ed80, 0xc0421ba940, 0x2, 0x2, 0x2c8ed80, 0xc0421ba940)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:653 +0x2a9
github.com/spf13/cobra.(*Command).ExecuteC(0x2c901c0, 0xc04207df70, 0x4044ab, 0xc04205e058)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:728 +0x305
github.com/spf13/cobra.(*Command).Execute(0x2c901c0, 0x49, 0x2c90400)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:687 +0x32
github.com/prvst/philosopher/cmd.Execute()
	/home/felipevl/go/src/github.com/prvst/philosopher/cmd/root.go:31 +0x34
main.main()
	/home/felipevl/go/src/github.com/prvst/philosopher/main.go:6 +0x27

Process finished, exit value: 2

Executing command:
$> philosopher_windows_amd64.exe filter --sequential --mapmods --pepxml D:\Temp --protxml D:\Temp\interact.prot.xml 
Process started
INFO[09:29:08] Processing peptide identification files      
FATA[09:29:08] No pepXML files found, check your files and try again 

Process finished, exit value: 1

Executing command:
$> philosopher_windows_amd64.exe report 
Process started
FATA[09:29:08] cannot restore serialized data structures: invalid argument 

Process finished, exit value: 1

Executing command:
$> philosopher_windows_amd64.exe workspace --clean 
Process started
INFO[09:29:09] Removing workspace                           
WARN[09:29:09] cannot remove the meta data: remove .meta\meta.bin: The process cannot access the file because it is being used by another process. 
INFO[09:29:09] Done                                         

Process finished, exit value: 0

=========================
===
===        Done
===
=========================
```

**Comment by andytyk** [comment]
That seems to be a compatibility issue with the mzML file and the reader library that MSFragger uses to read mzML files.  Can you e-mail me directly at andykong at umich.edu and provide me access to the file so we can troubleshoot?

**Comment by JesseIL** [comment]
@andytyk here they are:

[fragger.params.txt](https://github.com/chhh/MSFragger-GUI/files/1449443/fragger.params.txt)

[Human_SP_2017_Aug_crap.fasta.txt](https://github.com/chhh/MSFragger-GUI/files/1449458/Human_SP_2017_Aug_crap.fasta.txt)

**Comment by andytyk** [comment]
Are you possibly running Java 9?  If so, try running again with Java 8.
