### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by JesseIL** [chhh/MSFragger-GUI#21]
Hi,
I tried running an mgf file, none specific digestion and got the error below.
I set the memory to 80GB, since the machine has 130GB RAM.

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at x.a(Unknown Source)
	at v.a(Unknown Source)
	at e.a(Unknown Source)
	at MSFragger.main(Unknown Source)
	... 5 more
Caused by: java.lang.OutOfMemoryError: Java heap space

Any idea how to fix this?

**Comment by andytyk** [comment]
Can you share your fragger parameters file?

**Comment by JesseIL** [comment]
It is attached.

Y

On 6 Nov 2017, at 7:45 PM, Andy Kong <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you share your fragger parameters file?

**Comment by chhh** [comment]
@JesseIL When you reply be email to GitHub issues emails attachments are not added to the issue tracker, i.e. they are discarded. Please post your config file to this thread: [https://github.com/chhh/MSFragger-GUI/issues/21](https://github.com/chhh/MSFragger-GUI/issues/21)

**Comment by JesseIL** [comment]
[fragger.params.txt](https://github.com/chhh/MSFragger-GUI/files/1447654/fragger.params.txt)

**Comment by JesseIL** [comment]
@andytyk I uploaded the file.

**Comment by andytyk** [comment]
@JesseIL The search space is simply too large for MSFragger.  It runs out of memory while trying to count the number of peptides that it would generate so it doesn't even give a 'too many peptides' error message before crashing.  Do you really need all these modifications in conjunction with nonspecific digestion?  Can you potentially further restrict the range of permissible peptide lengths?  If neither of these options are a possibility for your project, then you'll have to wait for a future update of MSFragger that allows for partitioned databases.
