### ISSUE TITLE
cannot start MSFraggerGUI

### ISSUE THREAD

**Issue by talpa25** [chhh/MSFragger-GUI#32]
Dear developers,

when i try to run the msfraggerGUI.exe i double click the *.exe  and then nothing happens. When I try to run the java executable i'll get the following error:
\MSFragger-GUI_v4.1>java -jar MSFragger-GUI.jar
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Can't interpret variable mod from properties as delta mass and sites
        at umich.msfragger.params.fragger.MsfraggerParams.getVariableMods(MsfraggerParams.java:661)
        at umich.msfragger.gui.FraggerPanel.fillFormFromParams(FraggerPanel.java:224)
        at umich.msfragger.gui.FraggerPanel.initMore(FraggerPanel.java:115)
        at umich.msfragger.gui.FraggerPanel.<init>(FraggerPanel.java:85)
        at umich.msfragger.gui.MsfraggerGuiFrame.initMore(MsfraggerGuiFrame.java:145)
        at umich.msfragger.gui.MsfraggerGuiFrame.<init>(MsfraggerGuiFrame.java:128)
        at umich.msfragger.gui.MsfraggerGuiFrame$54.run(MsfraggerGuiFrame.java:3936)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

Do you know, what this means?
I have a windows 10 system with java 8  161 with german language settings.

Best

Roman

**Comment by chhh** [comment]
Hi Roman,
I see the place in the code that causes that, but I don't know how such a situation was made possible.  

Could you please first check if you have a file in your system temp directory, similar to `C:\Users\<your-user-name>\AppData\Local\Temp\fragger.params`?  
Delete it and try again.

Also, I've put out a new version (4.2) which is supposed to fix that bug.
Download link: https://github.com/chhh/MSFragger-GUI/releases/latest

**Comment by talpa25** [comment]
Dear Dmitry,

i checked the mentioned folder and YES there was a fragger.params that i've deleted. Afterwards i started the GUI and i wanted to run a open search on mzXML file but it gave me that error:
Executing command:
$> java -jar -Xmx5G C:\Users\Roman_Uni\Documents\MS_Daten\MS-XL-Tools\MSFragger\MSFragger.jar C:\Users\Roman_Uni\Documents\MS_Daten\20180108_TOC_mE\Ara MS Fragger\fragger.params C:\Users\Roman_Uni\Documents\MS_Daten\20180108_TOC_mE\20180108_mE_Ara_DMTMM1_75mM.mzXML 
Process started
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NumberFormatException: For input string: "0,000000"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
	at java.lang.Double.parseDouble(Unknown Source)
	at E.a(Unknown Source)
	at E.a(Unknown Source)
	at E.<init>(Unknown Source)
	at MSFragger.main(Unknown Source)
	... 5 more

MSFragger version MSFragger-20171106
(c) University of Michigan

**Comment by talpa25** [comment]
If i run MSFragger alone on the command line with selfmade *params 
[fragger_pisum.zip](https://github.com/chhh/MSFragger-GUI/files/1656046/fragger_pisum.zip) it runs smoothly. 
If i run the params created by the gui on the command line it gives me the same error as above.

**Comment by chhh** [comment]
@talpa25 Thanks for the input! I see the problem now, it's most likely due to locale settings so with German some text fields that are for numbers get formatted with a comma instead of a dot. I'll fix that!

**Comment by chhh** [comment]
@talpa25 can you please try the new version ([link](https://github.com/chhh/MSFragger-GUI/releases/tag/v4.3))?
The problem is I wasn't able to reproduce the issue even after changing the default locale on my system to German and installing the German layout, etc. But I put in all the changes I could think of to make that go away.

**Comment by talpa25** [comment]
Hey Dmitry,
i've tried to run the new MSFragger-GUI but it will not start (nor the*.exe or the java), when i try to run the java version it tells me the changelog.
C:\Users\Roman_Uni\Documents\MS_Daten\MS-XL-Tools\MSFragger>java -jar MSFragger-GUI.jar
MSFragger-GUI v4.3 changelog:
v4.3:
 - Locale dependency fix for MSfragger parameters panel.
 - Philosopher checks version comparing to GitHub at startup.
v4.2:
 - Fix the issue that Fragger panel constructor could cause IOException and prevent the whole app from loading.
v4.1:
 - Variable mod site definition warning text if cached from older versions.
 - Java 9 warning for Fragger.
 - Non-symmetric precursor mass tolerance and detection of "[*" for var mods.
 - Cache fragger params after a dry-run or a real run.
v4.0:
 - Added version check for MSFragger-GUI itself, comparing to GitHub.
 - Two way sync of decoy/tag prefix used by Peptide Prophet and Philosopher Report.
 - Fix how msfragger jar is auto-found.
 - Added version to msfragger properties.
 - MSFragger version check.


C:\Users\Roman_Uni\Documents\MS_Daten\MS-XL-Tools\MSFragger>start javaw -jar MSFragger-GUI.jar

C:\Users\Roman_Uni\Documents\MS_Daten\MS-XL-Tools\MSFragger>

The 4.2 version i can still execute and it runs smoothly beside the above mentioned problem with the fragger.params writing in german language context.

**Comment by chhh** [comment]
@talpa25 oh crap, I was testing changelog printing and accidentally published wrong version.  
I've re-uploaded [v4.3](https://github.com/chhh/MSFragger-GUI/releases/tag/v4.3), sorry about that.  

With your current jar that you have you should still be able to run it though `java -cp <path-to-gui-jar> umich.msfragger.gui.MsFraggerGui`. I only changed the default entry point in the manifest file.

**Comment by talpa25** [comment]
Dear Dmitry, 
now it works all perfect! I'm loving it. :) for the moment i'm checking the data analyse of the run. There are some questions, but i'm asking them in another thread, they don't belong here. You can close the thread.
many thanx & praises
Roman

**Comment by chhh** [comment]
Cool!
