### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ot0tot** [chhh/MSFragger-GUI#41]
Hi,

I'm trying to run MSFragger-GUI on Windows, and am getting a "java.lang.NullPointerException" error:

```
`Executing command:
$> java -jar C:\xxxx\yyyy\zzzz\MSFragger-20171106.jar C:\xxxx\yyyy\zzzz\run1\fragger.params C:\xxxx\yyyy\zzzz\mgf\QE05561-LUMOS.mzML C:\xxxx\yyyy\zzzz\mgf\QE05562-LUMOS.mzML C:\xxxx\yyyy\zzzz\mgf\QE05563-LUMOS.mzML C:\xxxx\yyyy\zzzz\mgf\QE05564-LUMOS.mzML 
Process started
MSFragger version MSFragger-20171106
(c) University of Michigan

Sequence database filtered and tagged in 5ms
Digestion completed in 26ms
Merged digestion results in 2ms
Sorting digested sequences...

	of length 7: 34
	of length 8: 43
	of length 9: 42
	of length 10: 30
	of length 11: 40
	of length 12: 36
	of length 13: 41
	of length 14: 33
	of length 15: 38
	of length 16: 45
	of length 17: 33
	of length 18: 51
	of length 19: 32
	of length 20: 22
	of length 21: 26
	of length 22: 31
	of length 23: 46
	of length 24: 29
	of length 25: 27
	of length 26: 24
	of length 27: 20
	of length 28: 27
	of length 29: 16
	of length 30: 16
	of length 31: 27
	of length 32: 14
	of length 33: 26
	of length 34: 14
	of length 35: 18
	of length 36: 16
	of length 37: 14
	of length 38: 16
	of length 39: 19
	of length 40: 6
	of length 41: 15
	of length 42: 20
	of length 43: 13
	of length 44: 15
	of length 45: 17
	of length 46: 21
	of length 47: 14
	of length 48: 3
	of length 49: 3
	of length 50: 1
	DONE
Removing duplicates and compacting...
Reduced to 1052  peptides in 105ms
Generating modified peptides...DONE in 28ms
Generated 1439 modified peptides
Merging peptide pools from threads... DONE in 2ms
Sorting modified peptides by mass...DONE in 2ms

Peptide index written in 87ms
Selected fragment tolerance 0.02 Da and maximum fragment slice size of 1312.79MB
136340 fragments to be searched in 1 slices (0.00GB total)
Operating on slice 1 of 1: 
299ms
	QE05561-LUMOS.mzML 
java.lang.NullPointerException
	at o.b(Unknown Source)
	at n.d(Unknown Source)
	at n.a(Unknown Source)
	at MSFragger.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
	
Error parsing: QE05561-LUMOS.mzML5388ms
	QE05562-LUMOS.mzML 
java.lang.NullPointerException
	at o.b(Unknown Source)
	at n.d(Unknown Source)
	at n.a(Unknown Source)
	at MSFragger.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

Error parsing: QE05562-LUMOS.mzML2009ms
	QE05563-LUMOS.mzML 
java.lang.NullPointerException
	at o.b(Unknown Source)
	at n.d(Unknown Source)
	at n.a(Unknown Source)
	at MSFragger.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

Error parsing: QE05563-LUMOS.mzML1614ms
	QE05564-LUMOS.mzML 
java.lang.NullPointerException
	at o.b(Unknown Source)
	at n.d(Unknown Source)
	at n.a(Unknown Source)
	at MSFragger.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

Error parsing: QE05564-LUMOS.mzML2196ms

Process finished, exit value: 0`
```

All subsequent steps fail because no pepXML files are written due to the java error. 

Any ideas?

Java Info:
java.version: 1.8.0_161
java.vm.specification.version: 1.8
java.vm.specification.vendor: Oracle Corporation
java.vm.specification.name: Java Virtual Machine Specification
java.vm.version: 25.161-b12
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.specification.version: 1.8
java.specification.vendor: Oracle Corporation
java.specification.name: Java Platform API Specification

**Comment by chhh** [comment]
Hi @ot0tot , would you mind sharing that particular mzML file?  
Most likely the problem is the file itself, as Fragger did start and digest the database. Might be a broken file, might be missing info in the file, might be something else.

**Comment by andytyk** [comment]
There also used to be a bug in MSFragger with extremely small databases.  It appears that you are using a recent enough version where that bug has been fixed.  Feel free to reach out directly to me at andykong at umich.edu with your files for debugging.

**Comment by ot0tot** [comment]
Emailed link to mzML file. Please let me know if you didn't receive it.

**Comment by ot0tot** [comment]
Issue solved with latest RC.
